// Placas x filamentos no simulador, demonstração, 1440 e 390 px.
// Uso: node ferramentas/teste-navegador/teste-placas.mjs [pasta dos prints]
// Cobre: Filamento sem coluna de gramas; matriz com uma linha por placa e uma coluna por cor;
// totais por cor, por placa e geral; gramas com vírgula; placa vazia avisa e não conta;
// tirar cor tira a coluna; G-code importado vira placa "fatiador" sem perda; placa manual na
// mesma cor soma perda só na parte digitada; sem rolagem horizontal da página em 390.
import { chromium } from 'playwright';
import http from 'http'; import fs from 'fs'; import os from 'os'; import path from 'path';
const OUT = process.argv[2] || '.';
const html = fs.readFileSync(new URL('../../index.html', import.meta.url), 'utf8').replace(/window\.M3_CONFIG = \{[\s\S]*?\};/, 'window.M3_CONFIG = {};');
const srv = http.createServer((q, r) => { r.writeHead(200, { 'content-type': 'text/html; charset=utf-8' }); r.end(html); }).listen(0);
const b = await chromium.launch();
let falhas = 0, total = 0;
const ok = (n, c, i = '') => { total++; console.log(`${c ? 'PASSOU' : 'FALHOU'} ${n} ${i}`); if (!c) falhas++; };
const num = (t) => Number(String(t).replace(/[^\d,]/g, '').replace(',', '.'));
const espera = (p, ms = 250) => p.waitForTimeout(ms);
const perto = (a, b, tol = 0.06) => Math.abs(a - b) <= tol;

const GCODE = path.join(os.tmpdir(), 'placa-teste.gcode');
fs.writeFileSync(GCODE, [
  '; generated by BambuStudio', '; filament_type = PLA;PLA', '; filament_colour = #1B1B1B;#EBF1F5',
  '; filament used [g] = 39.20, 12.00', '; estimated printing time (normal mode) = 4h 21m 0s', 'G28', ''].join('\n'));

async function menu(p, nome) {
  const item = p.locator('nav[aria-label="Menu"] button', { hasText: new RegExp(`^\\s*${nome}\\s*$`) }).first();
  if (!(await item.isVisible())) { await p.locator('button[aria-label="Abrir menu"]').first().click(); await espera(p); }
  await item.click(); await espera(p, 400);
}
const cel = (p, placa, cor) => p.locator(`.mz tbody tr:nth-child(${placa}) td:nth-of-type(${cor + 1}) input`).first();
const tempo = (p, placa) => p.locator(`.mz tbody tr:nth-child(${placa}) td.mz-t input`);
const metricaG = async (p) => num(await p.locator('.metricas > div').first().locator('b').innerText());
const perdas = async (p) => p.$$eval('.fila.sem-g', (xs) => xs.map((x) => { const i = [...x.querySelectorAll('input')].pop(); return i.disabled ? 0 : Number(i.value) / 100; }));
const semRolagem = (p) => p.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1);

for (const [w, h] of [[1440, 900], [390, 844]]) {
  const ctx = await b.newContext({ viewport: { width: w, height: h }, isMobile: w < 500, hasTouch: w < 500 });
  const p = await ctx.newPage(); const erros = [];
  p.on('pageerror', (e) => erros.push(e.message)); p.on('dialog', (d) => d.accept());
  await p.goto(`http://localhost:${srv.address().port}/`); await espera(p, 600);
  await p.click('button[type=submit]'); await espera(p, 600);
  await menu(p, 'Simulador');

  ok(`[${w}] Filamento sem coluna de gramas`, (await p.locator('.fila.sem-g input[id^="g"]').count()) === 0);
  ok(`[${w}] matriz começa com a placa 1`, await p.locator('.mz tbody tr').first().locator('th', { hasText: 'Placa 1' }).isVisible());

  // placa 1: 4h21, cor 1 com 39,2 g digitado com vírgula
  await tempo(p, 1).nth(0).fill('4'); await tempo(p, 1).nth(1).fill('21');
  await cel(p, 1, 1).fill('39,2'); await espera(p);
  // segunda cor e segunda placa
  await p.locator('.cartao', { has: p.locator('h2', { hasText: 'Filamento' }) }).getByRole('button', { name: 'Cor', exact: true }).click(); await espera(p);
  ok(`[${w}] cor nova vira coluna na matriz`, (await p.locator('.mz tbody tr').first().locator('td.mz-g').count()) === 2);
  await cel(p, 1, 2).fill('12'); await espera(p);
  await p.locator('.mz-caixa').getByRole('button', { name: 'Placa', exact: true }).click(); await espera(p);
  await tempo(p, 2).nth(0).fill('1'); await tempo(p, 2).nth(1).fill('10');
  await cel(p, 2, 2).fill('18,5'); await espera(p, 400);

  const pe = await perdas(p);
  const pe1 = pe[0], pe2 = pe[1];
  const rodape = (await p.locator('.mz tfoot').innerText()).replace(/\s+/g, ' ');
  ok(`[${w}] total de tempo das placas`, /5h31/.test(rodape), rodape);
  ok(`[${w}] total por cor e geral`, /39,20? g/.test(rodape) && /30,50? g/.test(rodape) && /69,70? g/.test(rodape), rodape);
  ok(`[${w}] gramas mostram vírgula`, (await cel(p, 2, 2).inputValue()) === '18,5');
  const esperado = 39.2 * (1 + pe1) + 30.5 * (1 + pe2);
  ok(`[${w}] filamento por peça soma as placas com a perda`, perto(await metricaG(p), esperado), `${await metricaG(p)} x ${esperado.toFixed(2)}`);
  ok(`[${w}] 2 placas na conta`, /em 2 placa/.test(await p.locator('.metricas').innerText()));

  // placa vazia: avisa e não conta como placa
  await p.locator('.mz-caixa').getByRole('button', { name: 'Placa', exact: true }).click(); await espera(p);
  ok(`[${w}] placa vazia avisa`, await p.locator('.mz-caixa .aviso.atencao', { hasText: 'placa 3 está vazia' }).isVisible());
  ok(`[${w}] placa vazia não entra na conta`, /em 2 placa/.test(await p.locator('.metricas').innerText()));
  if (w < 500) ok(`[${w}] sem rolagem horizontal com a matriz`, await semRolagem(p));
  await p.screenshot({ path: `${OUT}/placas-${w}.png`, fullPage: true });
  await p.getByRole('button', { name: 'Tirar placa 3' }).click(); await espera(p);
  ok(`[${w}] tirar placa`, (await p.locator('.mz tbody tr').count()) === 2);

  // tirar a segunda cor tira a coluna e as gramas dela
  await p.locator('.fila.sem-g').nth(1).getByRole('button', { name: 'Remover filamento' }).click(); await espera(p, 400);
  const rod2 = (await p.locator('.mz tfoot').innerText()).replace(/\s+/g, ' ');
  ok(`[${w}] tirar cor tira a coluna`, (await p.locator('.mz tbody tr').first().locator('td.mz-g').count()) === 1 && /39,20? g/.test(rod2) && !/30,5/.test(rod2), rod2);

  // G-code: placa do fatiador, sem perda
  await p.setInputFiles('input[type=file][accept^=".gcode"]', GCODE); await espera(p, 900);
  ok(`[${w}] importado vira placa com selo fatiador`, await p.locator('.mz tbody tr').first().locator('.selo-fat').isVisible());
  ok(`[${w}] placa do fatiador não soma perda`, perto(await metricaG(p), 51.2), String(await metricaG(p)));
  // placa manual na mesma cor: só a parte digitada soma perda
  await p.locator('.mz-caixa').getByRole('button', { name: 'Placa', exact: true }).click(); await espera(p);
  await tempo(p, 2).nth(1).fill('50'); await cel(p, 2, 2).fill('10'); await espera(p, 400);
  const pf = (await perdas(p))[1];
  ok(`[${w}] cor mista libera a perda`, pf > 0, String(pf));
  ok(`[${w}] perda só na placa manual`, perto(await metricaG(p), 51.2 + 10 * (1 + pf)), `${await metricaG(p)} x ${(51.2 + 10 * (1 + pf)).toFixed(2)}`);
  ok(`[${w}] placa 1 continua fatiador`, await p.locator('.mz tbody tr').first().locator('.selo-fat').isVisible());
  // mexer numa grama da placa do fatiador tira o selo
  await cel(p, 1, 1).fill('40'); await espera(p, 400);
  ok(`[${w}] editar placa do fatiador vira manual`, (await p.locator('.mz tbody tr').first().locator('.selo-fat').count()) === 0);
  if (w < 500) ok(`[${w}] sem rolagem horizontal no fim`, await semRolagem(p));
  await p.screenshot({ path: `${OUT}/placas-misto-${w}.png`, fullPage: true });

  ok(`[${w}] sem erro de página`, erros.length === 0, erros.join(' | '));
  await ctx.close();
}
await b.close(); srv.close();
console.log(`\n${total - falhas}/${total} passaram`);
process.exit(falhas ? 1 : 0);
